title: Jonna Singh Alvarado
email: jsinghal@bidmc.harvard.edu
description: Systems Neuroscientist
baseurl: "" 
url: "https://jonnasingh.github.io"
github_username: jonnasingh

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections for organizing content
collections:
  publications:
    output: true
